package SocialMedia.APIControllers;

import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import jakarta.servlet.http.HttpServletRequest;

@RestController
@RequestMapping("/api/policy")
public class PolicyAPIController {
	@GetMapping("")
	public String getPolicy(ModelMap model, HttpServletRequest request) {
		String policy = "<!DOCTYPE html>\r\n"
				+ "<html lang=\"vi\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <title>Chính Sách</title>\r\n"
				+ "    <style>\r\n"
				+ "        body {\r\n"
				+ "            font-family: Arial, sans-serif;\r\n"
				+ "            line-height: 1.6;\r\n"
				+ "            margin: 20px;\r\n"
				+ "            background-color: #f4f4f4;\r\n"
				+ "        }\r\n"
				+ "        .container {\r\n"
				+ "            max-width: 800px;\r\n"
				+ "            margin: auto;\r\n"
				+ "            background: #fff;\r\n"
				+ "            padding: 20px;\r\n"
				+ "            border-radius: 8px;\r\n"
				+ "            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n"
				+ "        }\r\n"
				+ "        h1, h2, h3, h4 {\r\n"
				+ "            color: #333;\r\n"
				+ "        }\r\n"
				+ "        h1 {\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "        ul {\r\n"
				+ "            list-style: none;\r\n"
				+ "            padding: 0;\r\n"
				+ "        }\r\n"
				+ "        ul li {\r\n"
				+ "            padding: 8px;\r\n"
				+ "            background: #e7e7e7;\r\n"
				+ "            margin-bottom: 8px;\r\n"
				+ "            border-radius: 4px;\r\n"
				+ "        }\r\n"
				+ "        a {\r\n"
				+ "            text-decoration: none;\r\n"
				+ "            color: #007BFF;\r\n"
				+ "        }\r\n"
				+ "        a:hover {\r\n"
				+ "            text-decoration: underline;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <div class=\"container\">\r\n"
				+ "        <h1>Chính Sách</h1>\r\n"
				+ "        <h2>Mục Lục:</h2>\r\n"
				+ "        <ul>\r\n"
				+ "            <li><a href=\"#muc-dich\">Mục Đích</a></li>\r\n"
				+ "            <li><a href=\"#du-lieu-ca-nhan\">1. Dữ Liệu Cá Nhân</a>\r\n"
				+ "                <ul>\r\n"
				+ "                    <li><a href=\"#thu-thap-du-lieu\">1.1. Thu thập Dữ liệu</a></li>\r\n"
				+ "                    <li><a href=\"#su-dung-du-lieu\">1.2. Sử dụng Dữ liệu</a></li>\r\n"
				+ "                    <li><a href=\"#chia-se-du-lieu\">1.3. Chia sẻ Dữ liệu</a></li>\r\n"
				+ "                    <li><a href=\"#bao-mat-du-lieu\">1.4. Bảo mật Dữ liệu</a></li>\r\n"
				+ "                    <li><a href=\"#quyen-loi-va-lua-chon\">1.5. Quyền lợi và Lựa chọn</a></li>\r\n"
				+ "                </ul>\r\n"
				+ "            </li>\r\n"
				+ "            <li><a href=\"#bai-dang\">2. Bài Đăng</a>\r\n"
				+ "                <ul>\r\n"
				+ "                    <li><a href=\"#quy-dinh-chung\">2.1 Quy Định Chung</a>\r\n"
				+ "                        <ul>\r\n"
				+ "                            <li><a href=\"#bao-luc-va-kich-dong\">2.1.1. Bạo Lực và Kích Động</a></li>\r\n"
				+ "                            <li><a href=\"#khieu-dam-va-nudity\">2.1.2. Khiêu Dâm và Nudity</a></li>\r\n"
				+ "                            <li><a href=\"#kich-thich-tinh-duc-va-bao-luc\">2.1.3. Kích Thích Tình Dục và Bạo Lực</a></li>\r\n"
				+ "                            <li><a href=\"#quay-roi-va-ky-thi\">2.1.4. Quấy Rối và Kỳ Thị</a></li>\r\n"
				+ "                            <li><a href=\"#ban-quyen-va-chia-se-thong-tin-ca-nhan\">2.1.5. Bản Quyền và Chia Sẻ Thông Tin Cá Nhân</a></li>\r\n"
				+ "                        </ul>\r\n"
				+ "                    </li>\r\n"
				+ "                    <li><a href=\"#quy-trinh-xu-ly\">2.2. Quy Trình Xử Lý</a></li>\r\n"
				+ "                    <li><a href=\"#phan-hoi-va-khieu-nai\">2.3. Phản Hồi và Khiếu Nại</a></li>\r\n"
				+ "                </ul>\r\n"
				+ "            </li>\r\n"
				+ "            <li><a href=\"#thay-doi-chinh-sach\">3. Thay đổi Chính sách</a></li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h2 id=\"muc-dich\">Mục Đích:</h2>\r\n"
				+ "        <p>Chính sách này nhằm bảo vệ cộng đồng người dùng và duy trì môi trường an toàn, tích cực trên ứng dụng mạng xã hội của chúng tôi. Đảm bảo rằng người dùng được thông báo rõ ràng về các quy định này và luôn có sự hỗ trợ khi cần thiết từ phía bạn. Chúng tôi cam kết hỗ trợ sự đa dạng, tôn trọng quan điểm và đảm bảo mọi người đều cảm thấy thoải mái khi sử dụng dịch vụ của chúng tôi.</p>\r\n"
				+ "        \r\n"
				+ "        <h2 id=\"du-lieu-ca-nhan\">1. Dữ Liệu Cá Nhân</h2>\r\n"
				+ "        <h3 id=\"thu-thap-du-lieu\">1.1. Thu thập Dữ liệu</h3>\r\n"
				+ "        <p>Chúng tôi thu thập các loại thông tin cá nhân từ người dùng của ứng dụng mạng xã hội này nhằm cung cấp trải nghiệm tốt nhất và cải thiện dịch vụ của chúng tôi. Các loại thông tin này bao gồm nhưng không giới hạn:</p>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Thông tin cá nhân: tên, địa chỉ email, số điện thoại, địa chỉ IP.</li>\r\n"
				+ "            <li>Thông tin hồ sơ: hình ảnh, giới tính, ngày sinh, quốc gia, sở thích, v.v.</li>\r\n"
				+ "            <li>Dữ liệu hoạt động: bài viết, bình luận, lượt thích, tương tác với nội dung, thời gian truy cập, v.v.</li>\r\n"
				+ "        </ul>\r\n"
				+ "        \r\n"
				+ "        <h3 id=\"su-dung-du-lieu\">1.2. Sử dụng Dữ liệu</h3>\r\n"
				+ "        <p>Chúng tôi sử dụng dữ liệu cá nhân của bạn để:</p>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Cung cấp và duy trì dịch vụ mạng xã hội của chúng tôi.</li>\r\n"
				+ "            <li>Cải thiện và tùy chỉnh trải nghiệm người dùng.</li>\r\n"
				+ "            <li>Phản hồi và hỗ trợ người dùng.</li>\r\n"
				+ "            <li>Phát triển và nâng cao tính năng của ứng dụng.</li>\r\n"
				+ "            <li>Tiếp thị và quảng cáo.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h3 id=\"chia-se-du-lieu\">1.3. Chia sẻ Dữ liệu</h3>\r\n"
				+ "        <p>Chúng tôi có thể chia sẻ thông tin cá nhân của bạn với các bên thứ ba trong các trường hợp sau:</p>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Với các đối tác cung cấp dịch vụ: để cung cấp các dịch vụ hỗ trợ và tích hợp.</li>\r\n"
				+ "            <li>Theo yêu cầu pháp lý: để tuân thủ các quy định pháp luật hoặc yêu cầu từ cơ quan thẩm quyền.</li>\r\n"
				+ "            <li>Trong các giao dịch doanh nghiệp: trong trường hợp tái tổ chức, sáp nhập, bán hoặc mua lại toàn bộ hoặc một phần của công ty.</li>\r\n"
				+ "            <li>Với sự đồng ý của người dùng: trong các trường hợp khác không được mô tả ở đây, chúng tôi sẽ thông báo và yêu cầu sự đồng ý của bạn trước khi chia sẻ thông tin cá nhân.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h3 id=\"bao-mat-du-lieu\">1.4. Bảo mật Dữ liệu</h3>\r\n"
				+ "        <p>Chúng tôi cam kết bảo vệ thông tin cá nhân của bạn và áp dụng các biện pháp bảo mật phù hợp để ngăn chặn truy cập trái phép, sử dụng sai mục đích, hoặc tiết lộ thông tin cá nhân của bạn.</p>\r\n"
				+ "        \r\n"
				+ "        <h3 id=\"quyen-loi-va-lua-chon\">1.5. Quyền lợi và Lựa chọn</h3>\r\n"
				+ "        <p>Người dùng có quyền:</p>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Truy cập, chỉnh sửa hoặc xóa thông tin cá nhân của mình.</li>\r\n"
				+ "            <li>Rút lại sự đồng ý cho việc thu thập hoặc sử dụng thông tin cá nhân.</li>\r\n"
				+ "            <li>Yêu cầu hỗ trợ hoặc có câu hỏi liên quan đến chính sách bảo mật và dữ liệu cá nhân.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h2 id=\"bai-dang\">2. Bài Đăng</h2>\r\n"
				+ "        <h3 id=\"quy-dinh-chung\">2.1 Quy Định Chung</h3>\r\n"
				+ "        <h4 id=\"bao-luc-va-kich-dong\">2.1.1. Bạo Lực và Kích Động</h4>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Không được phép chia sẻ hoặc tuyên truyền bất kỳ hình ảnh hoặc nội dung nào liên quan đến bạo lực, kích động, hoặc kích thích hành vi bạo lực.</li>\r\n"
				+ "            <li>Tất cả các hình ảnh hoặc video liên quan đến bạo lực phải được cảnh báo và chỉ dành cho người dùng trưởng thành.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h4 id=\"khieu-dam-va-nudity\">2.1.2. Khiêu Dâm và Nudity</h4>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Chúng tôi không chấp nhận bất kỳ hình ảnh, video hoặc nội dung nào liên quan đến khiêu dâm hoặc nudity.</li>\r\n"
				+ "            <li>Hình ảnh về nudity sẽ bị xóa ngay lập tức và người dùng có thể bị cấm hoạt động trên ứng dụng.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h4 id=\"kich-thich-tinh-duc-va-bao-luc\">2.1.3. Kích Thích Tình Dục và Bạo Lực</h4>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Mọi hình ảnh hoặc nội dung khuyến khích hoặc mô tả hành vi tình dục hoặc bạo lực đều bị cấm.</li>\r\n"
				+ "            <li>Nội dung về hành vi tình dục chỉ được chấp nhận khi được đồng ý và chỉ dành cho người trưởng thành.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h4 id=\"quay-roi-va-ky-thi\">2.1.4. Quấy Rối và Kỳ Thị</h4>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Quấy rối, kỳ thị hoặc bất kỳ hành vi nào gây tổn hại đến danh dự, uy tín hoặc an ninh của người khác đều không được chấp nhận.</li>\r\n"
				+ "            <li>Người dùng có thể bị xóa hoặc cấm sử dụng ứng dụng nếu vi phạm quy định này.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h4 id=\"ban-quyen-va-chia-se-thong-tin-ca-nhan\">2.1.5. Bản Quyền và Chia Sẻ Thông Tin Cá Nhân</h4>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Người dùng phải tuân thủ luật bản quyền và không chia sẻ thông tin cá nhân của người khác mà không có sự cho phép của họ.</li>\r\n"
				+ "            <li>Chúng tôi sẽ xóa bất kỳ nội dung vi phạm quy định bản quyền mà không cần thông báo trước.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h3 id=\"quy-trinh-xu-ly\">2.2. Quy Trình Xử Lý</h3>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Mọi bài đăng được kiểm duyệt bởi hệ thống và cộng đồng người dùng.</li>\r\n"
				+ "            <li>Bất kỳ nội dung vi phạm chính sách sẽ bị xóa ngay lập tức hoặc bị ẩn đi.</li>\r\n"
				+ "            <li>Người dùng có thể báo cáo bất kỳ nội dung nào họ cho là vi phạm chính sách.</li>\r\n"
				+ "            <li>Người dùng vi phạm chính sách có thể bị xóa bài đăng, tạm ngưng tài khoản hoặc bị cấm sử dụng ứng dụng tùy thuộc vào mức độ vi phạm.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h3 id=\"phan-hoi-va-khieu-nai\">2.3. Phản Hồi và Khiếu Nại</h3>\r\n"
				+ "        <ul>\r\n"
				+ "            <li>Chúng tôi luôn sẵn lòng lắng nghe phản hồi và khiếu nại từ cộng đồng người dùng.</li>\r\n"
				+ "            <li>Người dùng có thể liên hệ với chúng tôi thông qua kênh hỗ trợ để báo cáo nội dung vi phạm hoặc yêu cầu giải đáp thắc mắc liên quan đến chính sách này.</li>\r\n"
				+ "        </ul>\r\n"
				+ "\r\n"
				+ "        <h2 id=\"thay-doi-chinh-sach\">3. Thay đổi Chính sách</h2>\r\n"
				+ "        <p>Chính sách này có hiệu lực ngay lập tức sau khi công bố và có thể được cập nhật hoặc sửa đổi theo yêu cầu hoặc thay đổi trong luật pháp và xu hướng xã hội.</p>\r\n"
				+ "        <p>Chúng tôi có thể cập nhật Chính sách về Dữ liệu Cá Nhân này theo thời gian mà không cần thông báo trước. Bằng cách sử dụng ứng dụng của chúng tôi, bạn đồng ý với các thay đổi trong Chính sách này.</p>\r\n"
				+ "\r\n"
				+ "        <p>Ký Tên: <br>[PIE]</p>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n"
				+ "";
			
		return policy;
	}
}
